
 name: First.yml 
 on: push

 
 jobs :
   firstjob:
     name: First job
     runs-on: ubuntu-latest
     steps: 
       -name: Step1
        uses: actions/checkout@v2
       -name: Step2
        run: env | sort

   secondjob:
     needs: firstjob
     name: Second Job
     runs-on: windows-latest
     steps: 
      -name: Step1
       uses: actions/checkout@v2
      -name: Step2
       run: "Get-ChildItem Env: | Sort-Object Name"
